# Generated by Django 2.0.1 on 2018-02-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='magor',
            new_name='major',
        ),
    ]
