# Generated by Django 2.0.1 on 2018-02-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20180211_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
